### ISSUE TITLE
Изучение стандарта ERC20

### ISSUE THREAD

**Issue by BlockchainLabEOS** [BlockchainLabEOS/EOS-DVO#15]
https://theethereum.wiki/w/index.php/ERC20_Token_Standard

**Comment by liderako** [comment]
Пример хороший который многое обьяснить тоже -> [link](https://habrahabr.ru/post/326626/)

**Comment by liderako** [comment]
UML диаграмма стандартна erc20. Атрибуты не входят в стандарт но большинство токенов содержат эти атрибуты
![image](https://user-images.githubusercontent.com/25816656/32333963-d79ad3ce-bff1-11e7-813f-366ef94c6999.png)

**Comment by ioleksiu** [comment]
![image](https://user-images.githubusercontent.com/7544213/32367101-a16af336-c089-11e7-862a-c3b9863bf2df.png)
