### ISSUE TITLE
Running multi-node local testnet

### ISSUE THREAD

**Issue by liderako** [BlockchainLabEOS/EOS-DVO#17]
Изучить [README.md](https://github.com/EOSIO/eos/blob/master/README.md) по поводу нескольких нод. 
1. Изучить как запустить несколько нод.
 - Ответить на вопрос. Можно ли запустить несколько нод на двух-трех компьюетарх  либо пока это можно делать только на одном компьютере и при этом не одна нода, а две.
2. Запустить несколько нод.
3. Протестировать как все работает.

**Comment by liderako** [comment]
Ссылка из README.md [link](https://github.com/EOSIO/eos/blob/master/testnet.md)

**Comment by ioleksiu** [comment]
Во время изучения механизма запуска нескольких нод был сделан [перевод](https://github.com/ioleksiu/eos-rd/blob/master/docs/multi-node/%5BRU%5Dtestnet.md) документации.

**Comment by ioleksiu** [comment]
![screenshot from 2017-11-13 17-05-17](https://user-images.githubusercontent.com/7544213/32732362-ff1817c6-c894-11e7-8dad-09dedb525cd1.png)
