### ISSUE TITLE
DICE v2

### ISSUE THREAD

**Issue by BlockchainLabEOS** [BlockchainLabEOS/EOS-DVO#5]
Реализовать игру на базе смартконтактов EOS.

Player1 и Player2 ставят ставку по 10 единиц путем отправки транзакций на смарт контракт DICE. DICE проверяет что суммы транзакций от обоих игроков совпадают. Если ставки одинаковы, то DICE:
1) случайным образом определяет победителя
2) делает перевод всех ставок победителю
3) отправляет сообщение проигравшему.

В ходе реализации задания отрабатываются следующие функицональные возможности EOS:
-Создание акаунтов пользователей.
-Инициализация балансов.
-Перевод стредств между балансами пользователей.
-Отправка сообщений между акаунтами
-Работа с таблицами акаунта
-Создание обработчика сообщений (смартконтракт).

**Comment by liderako** [comment]
### Сообщения и обработчики
[TechnicalWhitePaper](https://github.com/EOSIO/Documentation/blob/master/ru-RU/TechnicalWhitePaper.md#Сообщения-и-обработчики)
> Каждый аккаунт имеет возможность отправлять структурированные сообщения другим аккаунтам, а также может определять процедуры обработки поступающих сообщений (скрипты). EOS.IO выделяет каждому аккаунту защищенную базу данных, доступ к которой имеют только собственные обработчики сообщений этого аккаунта. Обработчики сообщений могут посылать сообщения другим аккаунтам. Сочетание сообщений и их автоматизированных обработчиков и представляет собой смарт-контракты в EOS.IO.

Для решение задачи нужно отправлять сообщение из dice в player чтобы он изменял в себе таблицу.Для этого возможно нужно использовать [class Message](https://eosio.github.io/eos/classeos_1_1_message.html).

- Реализация находиться в [transaction.hpp](https://github.com/EOSIO/eos/blob/master/contracts/eoslib/transaction.hpp). 
(Комментарий в коде нету что усложняет его понимание)

- Возможно transaction.hpp связан с [transation.h](https://github.com/EOSIO/eos/blob/master/contracts/eoslib/transaction.h)

**Comment by liderako** [comment]
`class Message` и `class Transaction` используют функции которые обьявление в transation.h.
[Transaction C++ API](https://eosio.github.io/eos/group__transactioncppapi.html) использует функционал обернутый в классы про которые написана документация в  [Transaction C API](https://eosio.github.io/eos/group__transactioncapi.html).

Скорее всего решение как отправить сообщение от одного смарт-контракта другому описано в [Transaction C API](https://eosio.github.io/eos/group__transactioncapi.html).

**Comment by liderako** [comment]
[transaction.h](https://github.com/EOSIO/eos/blob/master/contracts/eoslib/transaction.h)
```
An inline message allows one contract to send another contract a message
which is processed immediately after the current message's processing
ends such that the success or failure of the parent transaction is 
dependent on the success of the message.
```
То что нам нужно возможно называют `inline message`. В комментариях есть несколько упоминание  встроенного сообщения. И видимо  чтобы отправить сообщение между аккаунтами нам нужен только Message.
1. Использавать messageCreate или один из конструкторов класса Message. Для создание сообщения.
2. Запросить как-то permission непонятно пока зачем.
3. И использовать messageSend либо send метод класса Message который `send a pending message as an inline message`

**Comment by asvirido** [comment]
Контракт proxy, использует классы Transaction & Message; Если разобрать его возможно можно разобраться как отправлять сообщение между аккаунтами.

**Comment by liderako** [comment]
Реализация [eos-contracts](https://github.com/asvirido/eos-contracts)
Контракты player и mydice
