### ISSUE TITLE
Message

### ISSUE THREAD

**Issue by liderako** [BlockchainLabEOS/EOS-DVO#8]
### Так вот основные вопросы которые возникают по классам Message and Transaction.

1. Не понятно что передают через классы в другие контракты. Они передают туда только handle?

2.  В конструторе Message используется typename Payload.
Сам конструктор вызывает функцию `messageCreate` и передает туда параметры разные.
`messageCreate(AccountName code, FuncName type, void const* data, int size);` 
В метод на место data передаем Payload. А  сам комментарий к функции такой 
`* @param data - the payload data for this message`.  Что это за параметр не понятно.

3. Можно ли передавать какую-то структуру в сообщении или текст другому аккаунту не понятно.Какого рода информацию мы можем передать туда. И как?

**Comment by liderako** [comment]
4. Как мы в коде можем достать PermissionName permission? При вызове этого метода что передавать во втором параметре? Как обратиться к permission?

```
void addPermissions(AccountName account, PermissionName permission) {
         messageRequirePermission(handle, account, permission);
}
```

**Comment by asvirido** [comment]
[transaction.h](https://github.com/EOSIO/eos/blob/master/contracts/eoslib/transaction.h)
5. В комментариях фигурирует слова про ` inline message `.  Что это такое?

**Comment by liderako** [comment]
Контракт proxy, использует классы Transaction & Message; Если разобрать его возможно можно разобраться как отправлять сообщение между аккаунтами.

**Comment by liderako** [comment]
[proxy.cpp](https://github.com/EOSIO/eos/blob/master/contracts/proxy/proxy.cpp)
```
 auto outMsg = Message(code, N(transfer), newTransfer, self, N(code));
```
          *   first argument AccountName code, which owns the contract code to execute
          *   second argument FuncName type, type of this message
          *   third argument Payload payload, the payload data for this message
          *
          *   Indicates that a given pending message requires a certain permission {
          *     fourth argument AccountName account
          *     fifth argument PermissionName permission 
          *   }
И тут есть несколько вопросов на которые нужно ответить прежде чем отправить сообщение.

1. Тут permission это N(code) что и не понятно. Почему именно так а не подругому? Только так можно или можно как-то подругому.
2. Второй параметр либо `action` либо структура в .abi в currency. Проблемы есть из-за того что 
они многие вещи називают одинаково. И точного описание что именно это не понятно.

**Comment by liderako** [comment]
Первый параметр в конструкторе кому отправить сообщение второй action который он получить  третий это структура или данные которые он получит. Permission не понятно зачем.
